### ISSUE TITLE
Could we get this merged into gomega proper?

### ISSUE THREAD

**Issue by zachgersh** [Benjamintf1/unmarshalledmatchers#1]
I literally had a need for this and the documentation pointed me here. I was wondering why we didn't just merge this (if you were so inclined).

**Comment by williammartin** [comment]
I think this set of matchers has demonstrated value to the community, and operates on a set of reasonably generic extractions that it's worth supporting in Gomega core. I'd be happy to help merge it in if someone opened a PR.

**Comment by Benjamintf1** [comment]
Sounds reasonablr to me.

**Comment by Benjamintf1** [comment]
started work.

**Comment by zachgersh** [comment]
@Benjamintf1 really appreciate this!

**Comment by Benjamintf1** [comment]
Just to let you know, I've halted work on this. It's not that It wouldn't be nice to have some of this functionality, it's that I think it's a little too messy right now to get into gomega I think(and it's hard to prioritize which features are important).
