### ISSUE TITLE
Use standard repo / package naming conventions to work with Dep

### ISSUE THREAD

**Issue by jontonsoup** [Benjamintf1/unmarshalledmatchers#3]
Thanks for this great library! 

One thing that has caused me severe trouble is the naming of the packages and repo. Because it doesn't follow conventions it makes it difficult to install with dep. We have a micro service architecture so I have run into this problem probably 5 times already (Wanted to see if it was something that would go away with practice). 

I think this package would have significantly more usage if it were easier to install! 

```
 Good package names are short and clear. They are lower case, with no under_scores or mixedCaps. They are often simple nouns...
```
https://blog.golang.org/package-names

**Comment by Benjamintf1** [comment]
I could totally change the name(I'll try to prioritize it). Right now the planned path forward is to move the functionality of this into base gomega, but I still havn't figured something out yet. I can go back to working on this, or the merge idea.

**Comment by jontonsoup** [comment]
@Benjamintf1 hopefully it can be merged into gomega! Thanks for your hard work!

**Comment by Benjamintf1** [comment]
@jontonsoup done.
